In [1]:
import cv2 as cv
import matplotlib.pyplot as plt
import numpy as np

In [2]:
img = cv.imread('C:/Users/Admin/Downloads/nine tail.jpg')
kernal = np.ones((3,3),np.float32)/9
filter = cv.filter2D(img,-1,kernal)
cv.imshow('image',img)
cv.imshow('filter2d',filter)
cv.waitKey(0)
cv.destroyAllWindows()

In [4]:
img

array([[[ 66,  66,  82],
        [ 42,  42,  58],
        [ 80,  80,  98],
        ...,
        [ 58,  54,  49],
        [ 58,  54,  49],
        [ 60,  56,  51]],

       [[ 64,  64,  80],
        [ 49,  49,  65],
        [ 90,  90, 108],
        ...,
        [ 60,  56,  51],
        [ 69,  65,  60],
        [ 63,  59,  54]],

       [[ 65,  65,  81],
        [ 53,  53,  69],
        [ 89,  89, 107],
        ...,
        [ 61,  57,  52],
        [ 72,  68,  63],
        [ 81,  77,  72]],

       ...,

       [[251, 253, 254],
        [248, 250, 251],
        [248, 250, 251],
        ...,
        [185, 208, 230],
        [188, 210, 235],
        [190, 213, 239]],

       [[253, 253, 253],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [189, 208, 229],
        [198, 219, 241],
        [195, 216, 238]],

       [[253, 253, 253],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [189, 208, 229],
        [200, 219, 240],
        [197, 215, 238]]

In [5]:
kernal

array([[0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.11111111]], dtype=float32)

In [6]:
img = cv.imread('C:/Users/Admin/Downloads/nine tail.jpg')
blur = cv.blur(img,(3,3))
cv.imshow('image',img)
cv.imshow('blur',blur)
cv.waitKey(0)
cv.destroyAllWindows()

# gaussian blur

In [7]:
img = cv.imread('C:/Users/Admin/Downloads/noise image.jpg')
Gblur = cv.GaussianBlur(img,(7,7),0)
cv.imshow('image',img)
cv.imshow('Gaussianblur',Gblur)
cv.waitKey(0)
cv.destroyAllWindows()

In [8]:
img.shape

(180, 252, 3)

In [9]:
img

array([[[ 6,  1,  3],
        [ 9,  4,  6],
        [10,  5,  7],
        ...,
        [ 7,  2,  3],
        [ 7,  2,  3],
        [ 6,  1,  2]],

       [[11,  6,  8],
        [ 9,  4,  6],
        [ 8,  3,  5],
        ...,
        [ 6,  1,  2],
        [ 6,  1,  2],
        [ 5,  0,  1]],

       [[15, 10, 12],
        [10,  5,  7],
        [ 5,  0,  2],
        ...,
        [ 9,  4,  5],
        [ 8,  3,  4],
        [ 8,  3,  4]],

       ...,

       [[20, 27, 46],
        [23, 30, 49],
        [25, 35, 53],
        ...,
        [ 4,  6, 14],
        [ 9, 11, 19],
        [ 7,  9, 17]],

       [[44, 51, 70],
        [37, 44, 63],
        [24, 34, 52],
        ...,
        [21, 23, 31],
        [25, 27, 35],
        [22, 24, 32]],

       [[43, 50, 69],
        [42, 49, 68],
        [30, 40, 58],
        ...,
        [12, 14, 22],
        [14, 16, 24],
        [11, 13, 21]]], dtype=uint8)

# bilateral filters

In [12]:
img = cv.imread('C:/Users/Admin/Downloads/noise image.jpg')
Bfilter = cv.bilateralFilter(img,9,50,50)
cv.imshow('image',img)
cv.imshow('Bilateral',Bfilter)
cv.waitKey(0)
cv.destroyAllWindows()

In [13]:
img

array([[[ 6,  1,  3],
        [ 9,  4,  6],
        [10,  5,  7],
        ...,
        [ 7,  2,  3],
        [ 7,  2,  3],
        [ 6,  1,  2]],

       [[11,  6,  8],
        [ 9,  4,  6],
        [ 8,  3,  5],
        ...,
        [ 6,  1,  2],
        [ 6,  1,  2],
        [ 5,  0,  1]],

       [[15, 10, 12],
        [10,  5,  7],
        [ 5,  0,  2],
        ...,
        [ 9,  4,  5],
        [ 8,  3,  4],
        [ 8,  3,  4]],

       ...,

       [[20, 27, 46],
        [23, 30, 49],
        [25, 35, 53],
        ...,
        [ 4,  6, 14],
        [ 9, 11, 19],
        [ 7,  9, 17]],

       [[44, 51, 70],
        [37, 44, 63],
        [24, 34, 52],
        ...,
        [21, 23, 31],
        [25, 27, 35],
        [22, 24, 32]],

       [[43, 50, 69],
        [42, 49, 68],
        [30, 40, 58],
        ...,
        [12, 14, 22],
        [14, 16, 24],
        [11, 13, 21]]], dtype=uint8)

In [14]:
img.shape

(180, 252, 3)

In [15]:
Bfilter

array([[[10,  5,  7],
        [10,  5,  7],
        [10,  6,  7],
        ...,
        [ 7,  2,  3],
        [ 7,  2,  3],
        [ 7,  2,  3]],

       [[11,  6,  8],
        [11,  6,  8],
        [11,  6,  8],
        ...,
        [ 7,  2,  3],
        [ 7,  2,  3],
        [ 7,  2,  3]],

       [[12,  7,  9],
        [11,  6,  8],
        [10,  5,  7],
        ...,
        [ 7,  2,  3],
        [ 7,  2,  3],
        [ 7,  2,  3]],

       ...,

       [[26, 32, 49],
        [27, 33, 50],
        [28, 34, 52],
        ...,
        [10, 11, 17],
        [13, 13, 19],
        [13, 13, 19]],

       [[32, 40, 58],
        [31, 39, 57],
        [28, 35, 53],
        ...,
        [14, 15, 22],
        [16, 17, 24],
        [15, 16, 23]],

       [[33, 41, 59],
        [33, 41, 59],
        [30, 38, 56],
        ...,
        [11, 12, 20],
        [13, 14, 21],
        [13, 14, 22]]], dtype=uint8)

In [21]:
img = cv.imread('C:/Users/Admin/Downloads/salt and pepper noise image.jpg')
medianFilter = cv.medianBlur(img,5)
cv.imshow('image',img)
cv.imshow('medianBlur',medianFilter)
cv.waitKey(0)
cv.destroyAllWindows()